// IF YOU CREATE WEBSOCKETS WITH NATIVE JS IN THE BROWSER,
// THEY'LL WORK FOR MOST MODERN BROWSERS, BUT THE SUPPORT
// FOR THEM IN OLDER BROWSERS ISNT QUITE THERE YET.
// SOMETHING WE CAN DO TO ALLEVIATE THIS IS USE "socket.io"

// SOCKET.IO IS A MODULE THAT WILL HELP US BUILD WEB SOCKETS
// THAT HAS ITS OWN CLIENT AND SERVER JAVASCRIPT. WHAT SOCKET
// IO DOES IS "FAIL BACK TO LONG POLLING" WHEN WEB SOCKETS
// AREN'T SUPPORTED. IF WEBSOCKETS AREN'T SUPPORTED IN
// THE BROWSER, THEN SOCKET IO WILL STILL WORK.
// IF WEBSOCKETS AREN'T SUPPORTED OH YOUR HOSTING, YOU CAN
// BUILD A WEBSOCKET APPLICATION THAT ENTIRELY USES
// LONG POLLING, SO THAT YOU CAN HAVE A SOCKET APPLICATION
// WORK WHERE WEBSOCKETS ARE NOT SUPPORTED.
