// SOCKETS ALLOW FOR A TRUE 2 WAY CONNECTION BETWEEN THE CLIENT
// AND THE SERVER. WEBSOCKETS USE THEIR OWN PROTOCOL TO SEND
// AND RECEIVE MESSAGES FROM A TCP SERVER.

// BEFORE SOCKETS WERE INTRODUCED, WE HAD NO WAY OF PUSHING
// DATA FROM THE SERVER TO THE BROWSER. THE BROWSER HAD TO
// CONSTANTLY CHECK THE SERVER API BY MAKING A GET REQUEST,
// TO CHECK IF THE STATE OF THE SERVER HAS CHANGE\D.

// WE CALL THIS "POLLING". "LONG POLLING" IS WHERE THE CLIENT
// REQ DATA FROM THE SERVER, AND REMAINS OPEN FOR A CERTAIN
// PERIOD OF TIME BEFORE CLOSING THE CONNECTION. THIS IS MORE
// EFFECIENT THAN POLLING BUT STILL NOT GREAT.

// WEB SOCKETS ALLOW US TO PERSIST OUR CONNECTION BETWEEN
// THE CLIENT AND THE SERVER SO WE CAN ALWAY XFER DATA.

// WEB SOCKETS ARE NOT LIMITED TO JUST THE BROWSER. ANY
// CLIENT CAN CONNECT TO YOUR SOCKET SERVER INCLUDING NATIVE
// APPLICATIONS.

// WEB SOCKETS USE THEIR OWN PROTOCOL. THEY CAN BE TRICKY TO
// SET UP. WE NEED A TCP SOCKET SERVER AND AN HTTP PROXY.
// THANKFULLY THERE ARE NODE MODULES TO HELP US .
